name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.13.1"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Start Server
        run: npm run start:ci

      - name: Wait for server to start
        run: sleep 10

      - name: Stop Server
        run: |
          pid=$(lsof -t -i:3000)
          if [ -n "$pid" ]; then
            kill -TERM $pid
          fi