name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.13.1"

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Start Server
        run: npm start
